### ISSUE TITLE
Add Youtube playlist AWS Cloud Pentesting

### ISSUE THREAD

**Issue by punitdarji** [redskycyber/CloudResources#3]
Thanks for sharing wonderful resource. I would like to share my youtube channel [Punit Darji](https://www.youtube.com/channel/UC44qxc7CcVSSCkRW2AOz7WA) where I have covered AWS cloud pentesting attacks and explained the entire attack. checkout given below playlist and add in videos section.
https://youtube.com/playlist?list=PLkfaD6nYyhM229NF7YtRaEOpU8Oc1hchR&si=I5U-sk9K-HxLSHg3

**Comment by redskycyber** [comment]
Added! Thanks for your contribution Punit
